### ISSUE TITLE
@RequestParam with no name / value is not supported 

### ISSUE THREAD

**Issue by mehtakaran9** [bliblidotcom/blibli-backend-framework#44]
If you use the following: 
`@RequestParam String requestParamOne`, it will not work because the name of the param is taken by the name or value of the annotation
`String name = StringUtils.isEmpty(annotation.name()) ? annotation.value() : annotation.name();`
Hence, the need for declaring it as follows: 
`@RequestParam("requestParamOne") String requestParamOne`
But ideally, it should be taken as the default if empty, from the Parameter's name field ( `parameter.getName()` )

**Comment by khannedy** [comment]
when java already compiled to binary code, we can not get information about the paramerName, so it's not recommended to get parameter name from parameter field value name, because it will be changed after compiled to binary code
